language: python

python:
    - "2.7"
    - "3.4"

env:
    - DJANGO=1.7.2 DJANGO_CONFIGURATION="Testing"
    - DJANGO=1.7.3 DJANGO_CONFIGURATION="Testing"

addons:
    postgresql: "9.3"

install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install -r requirements/test.txt

before_script:
    # check pep8
    - "pep8 --ignore=E501,E225"

    # create the db
    - psql -c 'create database volunteerapp;' -U postgres
    # migrate your DB for django projects
    - python volunteerapp/manage.py migrate --noinput

script:
    - py.test --flake --cov-report term --cov volunteerapp

after_success:
  - coveralls
